### ISSUE TITLE
еще один консультант —  leadback.ru

### ISSUE THREAD

**Issue by VanPetrov** [pafnuty/onlineConsultantBlocker#13]
ооочень сложно для меня, как для обычного пользователя здесь разобраться.
пошел на принцип, даже завел учетку на GitHub.
А всего-то хотел сообщить о еще одном "консультанте" —  leadback.ru

не уверен, что получилось поправить readme.md поэтому пишу здесь

**Comment by ildarkhasanshin** [comment]
легкий вариант (ваш)
1 написать в issue

вариант сложнее, но правильнее
1 нажимаете fork сверху справа
2 в своем форке редактируете README.md и online-consultant.txt по аналогии с другими строками
3 нажимаете на вкладку pull requests и там new pull request

**Comment by pafnuty** [comment]
@VanPetrov правильный способ - по большому счёту любой, который человек может осилить.
Для корректной блокировки надо бы для примера сайт, на котором расположен виджет сервиса т.к. блокировать сам сервис скорее всего бесполезно т.к. виджет может тянуться с другого домена.

**Comment by ildarkhasanshin** [comment]
в данном случае виджет тянется с того же сайта leadback.ru

**Comment by StackTheFennec** [comment]
Давайте я пулл внесу тогда? Раз никто так и не сделал
