### ISSUE TITLE
Дублируется блокировка api.leadiacloud.com

### ISSUE THREAD

**Issue by dartraiden** [pafnuty/onlineConsultantBlocker#19]
Собственно, сабж. В README и online-consultant.txt:

```
# Блокируем leadia.ru
127.0.0.1 api.leadiacloud.com
127.0.0.1 api.cloudleadia.com
```

```
# Блокируем leadiacloud.com
127.0.0.1 api.leadiacloud.com
```

Так и задумано? В противном случае, второй блок — лишний.

**Comment by dartraiden** [comment]
Ещё заметил, что в online-consultant.txt отсутствует блокировка me-talk.ru, присутствующая в README.

**Comment by pafnuty** [comment]
@dartraiden спасибо, поправим
