### ISSUE TITLE
Bitrix24

### ISSUE THREAD

**Issue by pfox7** [pafnuty/onlineConsultantBlocker#28]
было бы не плохо и его заблокировать :)

**Comment by pafnuty** [comment]
@pfox7 Есть пример сайта с консультантом bitrix24?

**Comment by pfox7** [comment]
https://www.bitrix24.ru/ :)

**Comment by userz58** [comment]
https://kercher-shop.ru/catalog/minimoyki/

**Comment by pafnuty** [comment]
Добавил целиком домен.
