### ISSUE TITLE
cleversite.ru

### ISSUE THREAD

**Issue by Dimox** [pafnuty/onlineConsultantBlocker#3]
Адрес виджета - http://cleversite.ru/cleversite/widget_new.php

**Comment by pafnuty** [comment]
блин, что-то мне нотификации не приходят с гитхаба о новых issue.
Сейчас добавим.

**Comment by pafnuty** [comment]
https://github.com/pafnuty/onlineConsultantBlocker/commit/18e4176135d8c4f619b78bca894017ab4bd86e85
