### ISSUE TITLE
Интеграция в uBlock

### ISSUE THREAD

**Issue by UksusoFF** [pafnuty/onlineConsultantBlocker#30]
Было бы хорошо если бы фильтр поддерживал uBlock и обновлялся в нем через веб.

**Comment by pafnuty** [comment]
@UksusoFF есть примеры подобных интеграций или описание api ublock?

**Comment by UksusoFF** [comment]
@pafnuty если в #29 вбить в поиск PornAway blacklist (ads), то там тоже вроде только hosts файл на который можно подписаться в том числе через uBlock.

Видимо можно просто с помощью магической ссылки:
`abp:subscribe?location=https%3A%2F%2Fraw.githubusercontent.com%2Fmhxion%2Fpornaway%2Fmaster%2Fhosts%2Fporn_ads.txt&amp;title=PornAway%20blacklist%20(ads)`
Подписаться прямо на hosts файл.

**Comment by UksusoFF** [comment]
Работает: https://gistpreview.github.io/?67303f91829cec7037e31d6cd0f13272
Т.е. достаточно будет добавить в каталог #29 и там уже будет ссылка на подписку.
