### ISSUE TITLE
"Недействительный список фильтров" при добавлении фильтров по ссылке в Adblock plus

### ISSUE THREAD

**Issue by victimmail** [pafnuty/onlineConsultantBlocker#43]
Используются
Firefox 82.0 (x64)
Adblock Plus 3.10

В настройках Adblock "Расширенные" нажимаю "Добавить список фильтра посредством URL", ввожу адрес 
https://raw.githubusercontent.com/pafnuty/onlineConsultantBlocker/master/online-consultant.txt

В результате этого фильтр в список адблока добавляется, но в колонке "Последнее обновление" пишет: "Недействительный список фильтров", и правила не срабатывают, консультанты не блокируются. Со стороны адблока информации об этом сообщении не нашел. 

![Screenshot_1](https://user-images.githubusercontent.com/75180861/100524652-a5cca200-31c2-11eb-814b-75479b0c1ddc.png)

**Comment by pafnuty** [comment]
Действительно выглядит странно.
Написал в поддержку ABP, возможно подскажут в чём причина.

**Comment by pafnuty** [comment]
Из поддержки ответили, что у файла был некоррекный "заголовок", не было текста `[Adblock Plus 2.0]`, теперь всё ок.
![image](https://user-images.githubusercontent.com/1635679/100592258-4d0b1f80-3310-11eb-9972-75686e8ba75c.png)
