### ISSUE TITLE
zopim.com

### ISSUE THREAD

**Issue by Dimox** [pafnuty/onlineConsultantBlocker#6]
Попался только что.

```
# Блокируем zopim.com
127.0.0.1 v2.zopim.com
```

**Comment by pafnuty** [comment]
@Dimox спасибо, добавлю.
В следующий раз дописывай пожалуйста `@pafnuty`, a то второй раз уже пропускаю тиккет :cry:

**Comment by pafnuty** [comment]
https://github.com/pafnuty/onlineConsultantBlocker/commit/ffb4237b4bf01aa3d0c922160c304ff95ac3b97b

**Comment by Dimox** [comment]
Окей, если не забуду.
